### ISSUE TITLE
onclick callback parameters

### ISSUE THREAD

**Issue by jcuenod** [jcuenod/imgCheckbox#18]
onclick should take at least the element that was selected and should, potentially include the full collection of elements.
Perhaps it could take a helper object that exposes certain functions which would return/do whatever is needed.

**Comment by ebrensi** [comment]
My pull request https://github.com/jcuenod/imgCheckbox/pull/19 addresses the simplest case you mentioned, namely the currently clicked element.

**Comment by jcuenod** [comment]
Nice work, thanks :)

**Comment by jcuenod** [comment]
I'm not 100% convinced by the way the docs suggest grabbing the `img` element at this point but since this library isn't regularly changing, it doesn't seem worth it to figure out some better™ solution so I've merged in #20 as well.

**Comment by ebrensi** [comment]
Maybe not the most elegant solution but It works, because I'm using it in my own project.  Thanks for the pull!

**Comment by jcuenod** [comment]
Ja, my problem would just be that it assumes the structure of the whole component. It's probably better to provide a method like `imgCheckbox.getImageElement(el)` or something. But like I say, it's not worth it when this works and the likelihood of the component structure changing is slim.
Glad you're using it :)

**Comment by ebrensi** [comment]
ok I might do that, but not today!

**Comment by jcuenod** [comment]
Well I've merged in your changes, so don't worry about it... the package functions as it should so my general philosophy has been to leave it until someone needs/wants new functionality. So thanks for the pull request!

**Comment by Nhawdge** [comment]
Could the demo site be updated with this version? I had used it as a reference and did not see this fix. 
Thanks!

**Comment by jcuenod** [comment]
@Nhawdge under [events](http://jcuenod.github.io/imgCheckbox/#events) it does include this documentation on the demo site... Maybe I'm missing something

**Comment by Nhawdge** [comment]
@jcuenod , Sorry about the confusion. The documentation is correct on the demo site, but the [.js file](http://jcuenod.github.io/imgCheckbox/assets/js/jquery.imgcheckbox.js) used by the demo site is a version behind. 

Thank you!

**Comment by jcuenod** [comment]
@Nhawdge thanks, done.
