### ISSUE TITLE
Help me use preselect

### ISSUE THREAD

**Issue by alanjholiveira** [jcuenod/imgCheckbox#25]
Hello, I would like to know how I can use Options to preselect the preselect using event onload: function () {}, as I have an ajax loading in the database the images select I want to put in the preselect to be able to show the selected images.

**Comment by jcuenod** [comment]
I'm not sure that I understand your question but the short answer is, preselect takes an array of indices that will be preselected. So to select the first image, your code is something like:

    $(".checkable").imgCheckbox({ preselect: [0] })

To select the first three images:

        $(".checkable").imgCheckbox({ preselect: [0, 1, 2] })

You will need to figure out which indices you want selected before you run `imgCheckbox`
