### ISSUE TITLE
Working on mobile?

### ISSUE THREAD

**Issue by terryb889** [jcuenod/imgCheckbox#28]
Hello, is anyone else having an issue running this on Mobile chrome/safari? 

It's working fine on Desktop versions...

**Comment by jcuenod** [comment]
It works fine for me on mobile chrome on Android (and Firefox Focus for that matter). I assume you are using an iPhone though and I believe that Chrome on iOS is forced to use Safari's engine which would explain a connected bug. I don't have any apple devices so there's no way for me to test this but if you figure something out and want to submit a PR, I'm willing to review an merge it.
